[package]
name = "example-core"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
tswift-ffi-macros = { path = "../../../tswift-ffi-macros" }

[build-dependencies]
home = "0.5"
which = "6"
